amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIAJQGGAOV5ESWA66PA
  secretKey: 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
  bucketName: traductor-documents-bucket
server:
    port: 5000